### ISSUE TITLE
patch command missing during build

### ISSUE THREAD

**Issue by vanhauser-thc** [ernw/static-toolbox#5]
I saw this error in the artifacts - seems like the patch command is now in a different install package:
```
patch /aarch64-linux-musl-cross/aarch64-linux-musl/include/asm/sigcontext.h < $GITHUB_WORKSPACE/patches/gdb/gdb-aarch64-header-sigcontext-fix.patch
/__w/_temp/c372c6a4-254c-4f75-8585-9671bf781585.sh: line 1: patch: not found
```

**Comment by takeshixx** [comment]
Thanks for reporting this! It seems like a couple of build processes are somehow affected.

**Comment by takeshixx** [comment]
I've updated various workflows and implemented release automation for the final binaries. Unfortunately, built artifacts expire after some time.

For now, there should be binaries of all current workflows in the release section. I will close this for now, feel free to open new issues in case something breaks again. :)
