### ISSUE TITLE
whishlist: strace

### ISSUE THREAD

**Issue by vanhauser-thc** [ernw/static-toolbox#8]
if you could add strace to the list of binaries - that would be awesome!
:)

**Comment by vanhauser-thc** [comment]
this is all it needs beside the cross compile stuff:
```
./bootstrap
export LDFLAGS="-static -pthread"
./configure
make
```

**Comment by takeshixx** [comment]
I also think that would be a great addition. I will work on this ASAP, thanks for the hint!

**Comment by vanhauser-thc** [comment]
thanks!
